pkg/api/core.go

advertise working version status

---

pkg/api/api_test.go
pkg/api/core.go
pkg/api/domains.go
pkg/api/input.go
pkg/api/projects.go
pkg/collector/fixtures/scrape3.sql
pkg/collector/fixtures/scrape4.sql
pkg/collector/scrape.go
pkg/collector/scrape_test.go
pkg/db/connection.go
pkg/limes/plugin.go
pkg/test/http.go
pkg/test/plugin.go

**DO NOT MERGE** without my consent.

implement quota setting

---

docs/example-config.yaml
main.go
pkg/collector/metrics.go
pkg/limes/config.go

Will merge this after giving it a proper testing in our staging cluster.

expose capacity/quota/usage data as Prometheus metrics

---

docs/example-config.yaml
pkg/plugins/capacity_cinder.go
pkg/plugins/capacity_nova.go
pkg/util/datatypes.go

add cinder and nova capacity plugins

---

pkg/plugins/manila.go

First take on manila quota plugin.

initial manila quota plugin

---

pkg/plugins/capacity_nova.go

ignore baremetal flavors in nova capacity plugin

---

pkg/limes/config.go
pkg/plugins/capacity_nova.go

configurable extra specs in nova capacity plugin

---

pkg/limes/config.go
pkg/plugins/capacity_swift.go
pkg/plugins/capacity_swift_health_statsd.go

add swift capacity plugin

---

docs/operators/config.md
pkg/limes/config.go
pkg/plugins/capacity_cinder.go

cinder: add filter for volume_backend_name

---

pkg/api/api_test.go
pkg/api/domains.go

Closes #36.
Checklist:
@auhlig @reimannf I whipped this up really quickly. A second set of eyes would be much appreciated.

api.PutDomain: create missing domain_resources entries

---

.gitignore
.travis.yml
Dockerfile
docs/operators/config.md
docs/operators/index.md
docs/operators/seeding.md
main.go
pkg/collector/consistency_test.go
pkg/collector/fixtures/checkconsistency-pre.sql
pkg/collector/fixtures/scandomains2.sql
pkg/collector/fixtures/scandomains3.sql
pkg/collector/fixtures/scandomains4.sql
pkg/collector/keystone.go
pkg/collector/keystone_test.go
pkg/limes/cluster.go
pkg/limes/config.go
pkg/limes/fixtures/quota-seed-invalid.yaml
pkg/limes/fixtures/quota-seed-valid.yaml
pkg/limes/seeds.go
pkg/limes/seeds_test.go
pkg/test/db.go

@reimannf Is this alright with you from the UI side of things (i.e. the stuff described in the docs)?
Checklist:

Quota seeding

---

docs/operators/config.md
pkg/limes/config.go
pkg/plugins/capacity_cinder.go
pkg/plugins/capacity_manila.go

According to @Carthaca's specifications.
Checklist:

add capacity plugin for Manila

---

docs/operators/config.md
pkg/limes/config.go
pkg/plugins/nova.go

add attribute "hypervisor" to instance subresources

---

docs/operators/config.md
docs/users/api-v1-specification.md
main.go
pkg/api/api_test.go
pkg/api/clusters.go
pkg/api/fixtures/cluster-list-detail.json
pkg/api/fixtures/start-data.sql
pkg/collector/capacity.go
pkg/collector/capacity_test.go
pkg/collector/fixtures/capacity_metrics.prom
pkg/collector/fixtures/scancapacity1.sql
pkg/collector/fixtures/scancapacity2.sql
pkg/collector/fixtures/scancapacity3.sql
pkg/collector/fixtures/scancapacity5.sql
pkg/collector/fixtures/scancapacity6.sql
pkg/db/migrations/006_add_cluster_resources_subcapacities.down.sql
pkg/db/migrations/006_add_cluster_resources_subcapacities.up.sql
pkg/db/models.go
pkg/dbdata/migrations.go
pkg/limes/cluster.go
pkg/limes/config.go
pkg/limes/plugin.go
pkg/plugins/capacity_cinder.go
pkg/plugins/capacity_manila.go
pkg/plugins/capacity_manual.go
pkg/plugins/capacity_nova.go
pkg/plugins/capacity_prometheus.go
pkg/plugins/capacity_sapcc_ironic.go
pkg/reports/cluster.go
pkg/test/plugin.go

subcapacities

---

docs/operators/metrics.md
pkg/collector/capacity.go
pkg/collector/metrics.go

Prometheus metric for failed capacitors
Checklist:
~~- [ ] If this PR is about a plugin, I tested the plugin against an OpenStack cluster.~~

Prometheus metric for failed capacitors

---

docs/users/api-v1-specification.md
pkg/api/api_test.go
pkg/api/core.go
pkg/api/domains.go
pkg/api/projects.go
pkg/api/quota_updater.go
pkg/collector/scrape.go
pkg/datamodel/domain_service.go
pkg/datamodel/project_service.go
pkg/limes/constraints.go
pkg/limes/constraints_test.go

As usual, this branch starts with the documentation. Code follows soon.
@reimannf Any comments on the API spec part?

add "simulate-put" endpoints for domains and projects

---

docs/operators/config.md
docs/users/api-v1-specification.md
pkg/api/api_test.go
pkg/api/clusters.go
pkg/api/fixtures/cluster-get-west-with-overcommit.json
pkg/api/fixtures/domain-get-france.json
pkg/api/fixtures/domain-get-germany.json
pkg/api/fixtures/domain-list.json
pkg/api/fixtures/project-get-berlin.json
pkg/api/fixtures/project-get-details-berlin.json
pkg/api/fixtures/project-get-dresden.json
pkg/api/fixtures/project-get-paris.json
pkg/api/fixtures/project-list.json
pkg/collector/capacity.go
pkg/collector/capacity_test.go
pkg/db/models.go
pkg/limes/cluster.go
pkg/limes/config.go
pkg/reports/cluster.go
pkg/reports/domain.go
pkg/reports/project.go

@reimannf You know the drill. Please review the `docs/` changes.

resource scaling relations and overcommitment

---

pkg/api/metrics.go
pkg/api/quota_updater.go

add metrics for quota auto-approval

---

pkg/plugins/swift.go

add metrics for object count per swift container

---

pkg/plugins/cinder.go
pkg/plugins/nova.go

availability zone support for subresources

---

docs/operators/config.md
pkg/api/api_test.go
pkg/api/core.go
pkg/api/fixtures/domain-get-germany.json
pkg/api/fixtures/domain-list-filtered.json
pkg/api/fixtures/domain-list.json
pkg/api/fixtures/project-get-dresden.json
pkg/api/fixtures/project-list-filtered.json
pkg/api/fixtures/project-list.json
pkg/api/projects.go
pkg/collector/capacity_test.go
pkg/collector/metrics.go
pkg/collector/scrape.go
pkg/core/cluster.go
pkg/core/config.go
pkg/datamodel/project_resource.go
pkg/datamodel/project_service.go
pkg/reports/cluster.go
pkg/reports/domain.go
pkg/reports/project.go
report_domain.go
report_project.go

To mark projects with a different consumption mode.

add annotations to domain/project resource reports

---

pkg/plugins/nova.go

Checklist:
Doc update will follow after code approval.
FYI @reimannf

nova: add ip address support for instances

---

pkg/plugins/capacity_nova.go

respect the VCenter HA reserve

---

pkg/plugins/cfm.go

Please don't merge yet
Checklist:
~~- [ ] I updated the documentation to describe the semantical or interface changes I introduced.~~

[cfm] Project usage based on storage_quota.usage.size

---

.dockerignore
.gitignore
docs/operators/config.md
pkg/plugins/nova.go

Add support for server group and its members

---

pkg/plugins/neutron.go

fix fmt import for neutron plugin

---

docs/operators/config.md
pkg/core/config.go
pkg/plugins/manila.go

@Carthaca Can you double-check that this has the correct semantics?

sharev2: manage replica quotas transparently

---

pkg/api/api_test.go
pkg/api/projects.go
pkg/api/quota_updater.go
pkg/collector/metrics.go
pkg/plugins/manila.go
pkg/plugins/neutron.go

Remove unused err

---

docs/operators/config.md
pkg/core/config.go
pkg/plugins/capacity_manila.go
pkg/plugins/client_manila.go
pkg/plugins/manila.go

To support the hypervisor-storage usecase. Putting this here as a draft since I will pick this up again next week to do the testing.
Checklist:

Manila: add virtual share types

---

pkg/plugins/capacity_nova.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/aggregates/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/aggregates/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/aggregates/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/aggregates/urls.go
vendor/modules.txt

Plugins capacity nova: convert to gophercloud

---

.gitignore
docs/users/api-v1-specification.md
pkg/api/api_test.go
pkg/api/core.go
pkg/api/errors.go
pkg/api/fixtures/inconsistency-empty.json
pkg/api/fixtures/inconsistency-list.json
pkg/api/fixtures/rate-scrape-error-empty.json
pkg/api/fixtures/rate-scrape-error-list.json
pkg/api/fixtures/scrape-error-empty.json
pkg/api/fixtures/scrape-error-list.json
pkg/reports/error.go
pkg/reports/inconsistency.go

Add API endpoint for scrape errors

---

internal/api/api_test.go
internal/collector/capacity_test.go
internal/core/cluster.go
internal/core/config.go
internal/core/constraints.go
internal/core/constraints_test.go
internal/core/errors.go
internal/core/resource_behavior.go
internal/reports/cluster.go
main.go

See detailed descriptions in the commit messages. My ultimate goal here is to get test coverage for this part of the code. There is more to do for that, but this PR is already large enough.
When merging this, please also merge the companion PR in the secrets repo.

refactor error handling etc. in the config loading and initialization stage

---

internal/collector/metrics.go
internal/collector/ratescrape.go
internal/collector/ratescrape_test.go
internal/collector/scrape.go
internal/collector/scrape_test.go
main.go

I'm putting this on myself as a reminder to merge this tomorrow and also adjust the alerts and dashboards for the changed metric structure.

convert scraping jobs to jobloop library

---

docs/operators/config.md
internal/plugins/manila.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/sharetypes/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/sharetypes/results.go
vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/sharetypes/urls.go
vendor/modules.txt

Please do not merge until the respective Manila metrics (including sapcc/helm-charts#5625) have been rolled out to all prod regions.
@Carthaca Please let me know when that has happened.

plugins/manila: add AZ awareness

---

internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/fixtures/capacity_scrape_with_commitments.sql
internal/core/resource_behavior.go
internal/datamodel/confirm_project_commitments.go

confirm pending commitments after capacity scrape

---

main.go

transfer commitment API returns CORS error otherwise

Fix: Allow Transfer-Token header.

---

go.mod
go.sum
internal/api/fixtures/project-get-paris.json
internal/api/fixtures/start-data.sql
internal/reports/project.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/report_project.go
vendor/modules.txt

@VoigtS As discussed on the phone.

report max_quota_from_admin on project level

---

internal/api/api_test.go
internal/api/projects.go

api: do not allow to set max_quota for NoQuota resources

---

internal/collector/fixtures/scrape_metrics.prom
internal/collector/fixtures/scrape_metrics_skipzero.prom
internal/collector/scrape_test.go
internal/collector/sync_quota_to_backend.go
internal/db/migrations.go
internal/db/models.go

Something is awry with this new jobloop, and I don't know what. For now, this might improve visibility into where the jobloop gets stuck.

add project_resources.quota_sync_duration_secs

---

docs/users/api-spec-resources.md
internal/api/api_test.go
internal/api/fixtures/cluster-get-west-filtered.json
internal/api/fixtures/cluster-get-west-with-overcommit-and-v2-api.json
internal/api/fixtures/cluster-get-west-with-overcommit.json
internal/api/fixtures/cluster-get-west-with-v2-api.json
internal/api/fixtures/cluster-get-west.json
internal/api/fixtures/domain-get-france.json
internal/api/fixtures/domain-get-germany.json
internal/api/fixtures/domain-list-filtered.json
internal/api/fixtures/domain-list-with-v2-api.json
internal/api/fixtures/domain-list.json
internal/api/fixtures/project-get-berlin.json
internal/api/fixtures/project-get-details-berlin.json
internal/api/fixtures/project-get-dresden.json
internal/api/fixtures/project-get-paris.json
internal/api/fixtures/project-list-filtered.json
internal/api/fixtures/project-list-with-v2-api.json
internal/api/fixtures/project-list.json
internal/collector/capacity_scrape_test.go
internal/collector/fixtures/capacity_metrics.prom
internal/collector/fixtures/ratescrape_metrics.prom
internal/collector/fixtures/ratescrape_metrics_skipzero.prom
internal/collector/fixtures/scrape_metrics.prom
internal/collector/fixtures/scrape_metrics_skipzero.prom
internal/collector/keystone_test.go
internal/collector/ratescrape_test.go
internal/collector/scrape_test.go
internal/core/config.go
internal/test/setup.go

Please check the commit messages for details.

remove remaining support for HierarchicalQuotaDistribution

---

internal/collector/metrics.go

As discussed over lunch, and also explained in the code comment near the bottom.

try to reduce the memory footprint of collector metrics

---

docs/operators/config.md
internal/plugins/capacity_nova.go
internal/plugins/nova/binpack_simulation.go

capacity-nova: make scoring function for placement configurable

---

docs/operators/config.md
internal/plugins/capacity_manila.go

capacity-manila: distribute to snapmirror_capacity, too

---

internal/plugins/swift.go

Otherwise we will inhibit the creation of Swift accounts, which is triggered through assignment of base quota.

plugins/swift: do not apply MaxQuota for uncreated accounts

---

internal/plugins/capacity_cinder.go
internal/plugins/capacity_manila.go

Same reasoning as in 9ee7f396549f519ad29f47b908dc112bc38e9754: If pools in the various decommissioning states are entirely ignored, this will underestimate real capacity too much. Instead, those pools are only considered up to their actual usage, and unused capacity is ignored.
Along the way, I also aligned the behavior of both capacity plugins. Manila pools with unknown hardware states will now be considered as live, same as for Cinder pools.
I tested this in eu-de-1, which has pools in decom on both services, and the aggregate numbers changed in the way that I expected.

capacity-{cinder,manila}: do not ignore usage in decommissioning pools

---

internal/datamodel/apply_computed_project_quota.go
internal/datamodel/apply_computed_project_quota_test.go

Also, I'm pulling up the calculation for that one level higher to avoid repeating the same calculation multiple times.

ACPQ: add debug log for the allowsQuotaOvercommit decision

---

docs/operators/config.md
internal/plugins/capacity_prometheus.go

Please only merge together with the forthcoming secrets PR.

capacity-prometheus: add AZ awareness

---

docs/operators/config.md
internal/core/resource_behavior.go
internal/datamodel/allocation_stats.go
internal/datamodel/allocation_stats_test.go
internal/datamodel/confirm_project_commitments.go

This turned out way easier than I expected.

add resource_behavior[].commitment_until_percent

---

internal/datamodel/allocation_stats.go
internal/datamodel/confirm_project_commitments.go

This part is extremely difficult to simulate in vitro, so I want to be able to observe it in vivo.

add debug log for commitment decisions

---

internal/api/api_test.go
internal/api/fixtures/cluster-get-west-with-v2-api.json
internal/api/fixtures/cluster-get-west.json
internal/api/fixtures/domain-get-france.json
internal/api/fixtures/domain-get-germany.json
internal/api/fixtures/domain-list-with-v2-api.json
internal/api/fixtures/domain-list.json
internal/api/fixtures/project-get-berlin-v2-api.json
internal/api/fixtures/project-get-berlin.json
internal/api/fixtures/project-get-details-berlin.json
internal/api/fixtures/project-get-dresden.json
internal/api/fixtures/project-get-paris.json
internal/api/fixtures/project-list-with-v2-api.json
internal/api/fixtures/project-list.json
internal/core/resource_behavior.go

Also, there apparently was no testcase for the Category field yet, so I added one.

fix category mapping

---

go.mod
go.sum
vendor/github.com/sapcc/go-api-declarations/cadf/event.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/commitment.go
vendor/modules.txt

Bump go-api declarations to 1.12.4

---

internal/plugins/capacity_prometheus.go

We had an incident in QA this morning, where kube-state-metrics was not being scraped by Prometheus. This caused several capacity scans that expressions like `$FACTOR * count(kube_pod_labels{$LABELS})` to return a result of 0. This was not covered by an absent-alert because we only have these autogenerated from PrometheusRules, not from the queries that are stored in the Limes config file. By ingesting a capacity value of 0 as valid, we run ApplyComputedProjectQuota on the respective resource and assign a quota of 0 everywhere.
Options considered:
- We could add alerts for `absent()` of the relevant metrics.
- Problem: need to maintain these separately from the Limes config file, will likely drift out of sync
- We could add `> 0` to the end of every query, to make it produce no result …

capacity-prometheus: fail if capacity is 0 unless explicitly allowed

---

internal/api/commitment.go
internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/metrics.go
internal/collector/scrape.go

Followup for #543. See commit messages for details.

fix usage of API identifiers in DB queries

---

internal/core/resource_behavior.go

CBR has confirmed that they don't need this anymore.

remove ContainedIn compat

---

internal/collector/metrics.go

The regex stuff in `BehaviorForResource` turned up as extremely expensive in real-world CPU profiles.

data-metrics: add cache for computed ResourceBehavior

---

internal/liquids/cinder/usage.go

If a volume was moved to a different project after taking snapshots, we might only see a snapshot without any volumes associated to it in the same project. This should not be an error, so we fall back on querying the individual volume residing in another project with our cloud-admin privileges.
This was not a problem in the pre-LIQUID implementation because that one just silently and incorrectly assumed that all snapshots without volume belonged to the default volume type.

liquid-cinder: fix placement sensing for snapshots on transfered volumes

---

internal/collector/metrics.go

I want to use this to filter resources in alerts.

add metric: limes_available_commitment_duration

---

internal/db/migrations.go

I verified this by running tests on a fresh test DB on both `master` and this branch and checking that `./testing/with-postgres-db.sh pg_dump -U postgres -h 127.0.0.1 -p 54321 -d limes -s` produces no diff.

rollup DB migrations

---

internal/plugins/capacity_sapcc_ironic.go

I don't know why I originally thought this needs a separate API call for each node, but after checking again now, the `retired` attribute is definitely already present in the main node list that we pull at the start, so we can save 1000+ API calls on large regions here.
Tested in a small prod region that currently has a retired node. Output is identical before and after the change.

plugins/ironic: optimize node listing

---

internal/liquids/ironic/capacity.go

liquid-ironic: report all AZs required by AZAwareResourceTopology

---

internal/reports/domain.go

Same as the previous handled cluster and project APIs. I wanted to include test cases in here for all cases, but that will be another case.

fix: domain API acces to any az

---

CONTRIBUTING.md

Remove references to with-postgres-db.sh from contribution guide

---

docs/liquids/nova.md
internal/liquids/nova/capacity.go

liquid-nova: fix pooled capacity calculation

---

internal/liquids/nova/capacity.go

liquid-nova: fix potential uint underflows in capacity calculation

---

internal/liquids/nova/binpack_simulation.go
internal/liquids/nova/capacity.go
internal/plugins/capacity_nova.go

liquid-nova: favor non-gp hypervisors in placement simulation

---

docs/operators/config.md
go.mod
go.sum
internal/collector/expiring_commitments.go
internal/collector/expiring_commitments_test.go
internal/core/cluster.go
internal/core/config.go
internal/datamodel/confirm_project_commitments.go
main.go
vendor/github.com/majewsky/gg/LICENSE
vendor/github.com/majewsky/gg/option/option.go
vendor/modules.txt

make MailConfiguration optional

---

main.go

Check database connection in healthcheck

---

internal/api/projects.go
internal/liquids/nova/hypervisor_selection.go

Run go's modernize tool

---

Makefile.maker.yaml

enable golang.autoupdateableDeps

---

go.mod
go.sum
internal/core/config.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/commitment.go
vendor/github.com/sapcc/go-api-declarations/liquid/availability_zone.go
vendor/github.com/sapcc/go-api-declarations/liquid/doc.go
vendor/github.com/sapcc/go-api-declarations/liquid/validation.go
vendor/modules.txt

This makes use of the new `AvailabilityZone.IsReal()` function that I added for this purpose.

bump go-api-declarations, validate that configured AZs are not pseudo-AZs
