sapcc/limes

pkg/limes/config.go

If cluster.auth section is not provided in config.yaml, the validation fails
because of nil pointer when accessing cluster.Auth.AuthURl. To avoid segfault
and still inform user about missing values just create an empty struct.

Prevent nil pointer access in config validate

---

docs/operators/config.md
pkg/plugins/nova.go

Basicly we need to discuss 2 things: 
* Flavors are cached and not invalidated, as changing **should** not be possible
* Access to cache is not thread safe as the current assumption is that the nova plugin will only scrape on project at once
Checklist:

Resolving flavors for compute instance subresource

---

docs/operators/metrics.md
pkg/collector/fixtures/scrape_metrics.json
pkg/collector/metrics.go
pkg/collector/scrape.go

It turned out that cluster is too generic for the configured OpenStack
clusters. E.g Prometheus federation might add the same label as well.
To avoid further confusions rename the label to os_cluster.
Checklist:
~~- [ ] If this PR is about a plugin, I tested the plugin against an OpenStack cluster.~~

Relabel metrics from `cluster` to `os_cluster`

---

docs/operators/metrics.md
pkg/collector/metrics.go
pkg/collector/scrape.go
pkg/limes/plugin.go
pkg/plugins/cinder.go
pkg/plugins/designate.go
pkg/plugins/manila.go
pkg/plugins/neutron.go
pkg/plugins/nova.go
pkg/plugins/swift.go

This is useful for our internal alerting which groups alerts by product name, e.g. "nova" instead of "compute".
Checklist:

add "service_name" label to scraping metrics that contains backend service's product name

---

docs/operators/config.md
pkg/plugins/capacity_nova.go
pkg/plugins/capacity_sapcc_ironic.go
pkg/plugins/client_ironic.go
pkg/plugins/constants.go
pkg/plugins/nova.go

~Regarding testing: It basically works, but the RAM values in our Ironic DBs look weird, so maybe we have to fix those to conduct an actual test.~ Test was successful in Sterling DC after RAM values were fixed in Ironic.
Checklist:

add sapcc-ironic capacity plugin

---

pkg/plugins/capacity_manila.go

I just copied the way of providing a url param from https://github.com/sapcc/limes/blob/05ecf7cde6734a445cf2614fd8fec346ae89474e/pkg/plugins/cinder.go#L92 and extracted the param from the python-manilaclient api debug
i.e. not tested, but I'm quite certain it works if there are no syntax errors

[capacity_manila] filter by default share-type

---

pkg/plugins/swift.go

If a swift account was deleted but not yet reaped, a client will receive
HTTP Status Code 410 (Gone). After reaping clients will get 404.
This case was not yet handled from limes. This will treat it like not found
and prevent scraping errors.
Checklist:

Swift Plugin - Respect Account Status 410

---

pkg/api/input.go
pkg/api/input_test.go

Another addition to make reuse easier. This time marshalling the `ServiceQuota`.

Marshalling support for ServiceQuotas

---

pkg/reports/project.go
pkg/reports/project_test.go
pkg/util/datatypes.go

This PR adds `UnmarshalJSON` functions to the project types. This allows to reuse the `Project` for retrieving responses from Limes.

implements unmarshalling support for projects

---

pkg/api/domains.go
pkg/api/projects.go
pkg/audit/log.go

Progress:
* Audit events for token authentication failure is a bit tricky, need to work on that.
* The rest of the error types for which we need audit events have been implemented.

Support audit events for rejected quota changes

---

.gitignore
docs/operators/config.md
pkg/plugins/cfm.go
pkg/util/datatypes.go
pkg/util/datatypes_test.go

~WIP because scraping fails on eu-de-1 with the Limes service user. CFM colleagues are looking into this.~ Resolved, although I have to add the superfluous `X-Project-Id` header to make it work.
Checklist:

add CFM quota plugin

---

pkg/api/fixtures/start-data-inconsistencies.sql
pkg/api/fixtures/start-data.sql
pkg/collector/fixtures/checkconsistency1.sql
pkg/collector/fixtures/checkconsistency2.sql
pkg/collector/fixtures/scandomains1.sql
pkg/collector/fixtures/scandomains2.sql
pkg/collector/fixtures/scandomains3.sql
pkg/collector/fixtures/scandomains4.sql
pkg/collector/fixtures/scrape-autoapprove1.sql
pkg/collector/fixtures/scrape-autoapprove2.sql
pkg/collector/fixtures/scrape-failures1.sql
pkg/collector/fixtures/scrape-failures2.sql
pkg/collector/fixtures/scrape-failures3.sql
pkg/collector/fixtures/scrape1.sql
pkg/collector/fixtures/scrape2.sql
pkg/collector/fixtures/scrape3.sql
pkg/collector/fixtures/scrape4.sql
pkg/collector/fixtures/scrape5.sql
pkg/collector/fixtures/scrape6.sql
pkg/collector/fixtures/scrape7.sql
pkg/collector/fixtures/scrape8.sql
pkg/collector/scrape.go
pkg/datamodel/project_resource.go
pkg/datamodel/project_service.go
pkg/db/migrations.go
pkg/db/models.go

With this, it will be possible to detect quota-mismatch inconsistencies in pure SQL without having to compute burst multipliers in the SQL expression.
Will merge this on Monday.
@talal When this is merged, rebase #74 onto this and use the new column in the SQL statements so that you don't have to fiddle with quota calculations in Go.
@reimannf FYI

add new column `project_resources.desired_backend_quota`

---

pkg/plugins/capacity_sapcc_cfm.go
pkg/plugins/client_cfm.go

CFM: compute correct capacity when duplicate pools are reported

---

pkg/plugins/cfm.go

Previously `usage.potential_growth_size` was used to report the usage with auto-grow option. We switch back to the real size used.
Want to hold that back until billing and reporting is informed.
Checklist:

Report on size_used for CFM usage

---

docs/operators/config.md
pkg/core/auth.go

allows to configure OpenStack endpoint type to use
Checklist:

added interface option to cluster auth section

---

pkg/plugins/manila.go

@chuan137 Does this look plausible to you?

do not double-count Manila physical usage during share migration

---

docs/operators/config.md
pkg/collector/capacity.go
pkg/core/config.go
pkg/core/plugin.go
pkg/plugins/capacity_cinder.go
pkg/plugins/capacity_manila.go
pkg/plugins/capacity_nova.go
pkg/plugins/capacity_sapcc_ironic.go
pkg/plugins/client_placement.go
pkg/test/plugin.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/results.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors/urls.go
vendor/modules.txt

@reimannf This is looking good from my side, but the numbers are different with and without Placement API. That's to be expected, otherwise we wouldn't need to bother with this, but we should probably validate in some way the numbers that the Placement API gives us.
To test-drive this, checkout this branch and run
```
make && ./build/limes test-scan-capacity eu-de-1.yaml ccloud
```
where `eu-de-1.yaml` is in the Gist that I sent you via chat. Toggle the config option `use_placement_api` in that file to check before vs. after.

use Placement API to gather hypervisor capacity/usage

---

docs/operators/config.md
pkg/plugins/manila.go

manila: use the new netapp exporter metric format

---

pkg/plugins/neutron.go
vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/results.go
vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/urls.go
vendor/modules.txt

This change introduces a pre-flight check for the neutron plugin that checks
if the lbaasv2 extension is enabled for setting lbaasv2 related quotas.
TLDR: Now works lbaasv2-less neutrons, since lbaasv2 is dropped with train.
Checklist:

check lbaasv2 support

---

pkg/plugins/neutron.go

This PR changes scraping for Octavia quota usage metrics to use new endpoint `quota_usage` instead of counting resources one by one.
Based on https://github.com/sapcc/octavia/pull/16
**⚠️DO NOT MERGE THIS PR BEFORE OCTAVIA'S ONE⚠️**
Checklist:

Use quota_usage endpoint in Octavia API instead of counting.

---

pkg/plugins/capacity_sapcc_ironic.go

Add availability zone and state info to Ironic node's subcapacities

---

go.sum
pkg/plugins/cinder.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/results.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/urls.go
vendor/modules.txt

Checklist:
Sadly Gophercloud does not provide a map string for quota sets https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/quotasets/results.go#L163

Plugins cinder: convert to gophercloud

---

pkg/api/api_test.go
pkg/api/clusters.go
pkg/api/core.go
pkg/api/domains.go
pkg/api/fixtures/project-get-berlin-only-rates.json
pkg/api/fixtures/project-get-paris-only-default-rates.json
pkg/api/fixtures/start-data-minimal.sql
pkg/api/fixtures/start-data.sql
pkg/api/projects.go
pkg/reports/project.go

As explained in the commit messages and code comments.
Checklist:

rewrite reports.GetProjects() into a streaming style to limit peak memory usage

---

docs/users/api-v1-specification.md
pkg/api/api_test.go
pkg/api/core.go
pkg/api/fixtures/cluster-get-west-filtered.json
pkg/api/fixtures/cluster-get-west-no-resources.json
pkg/api/fixtures/cluster-get-west-with-overcommit.json
pkg/api/fixtures/cluster-get-west.json
pkg/api/fixtures/project-get-berlin-only-rates.json
pkg/api/fixtures/project-get-dresden-only-rates.json
pkg/api/fixtures/project-get-paris-only-default-rates.json
pkg/api/fixtures/project-list-only-rates.json
pkg/api/projects.go
pkg/api/rates.go
pkg/reports/cluster.go
pkg/reports/project.go

During #135, I realized that having two types of differently-shaped data coming from different data sources (resource data and rate data) in the same API leads to an unnecessarily complex implementation and a lot of pain in general. Since the only user for the rate data is CBR (who collect Cronus rate usage data for billing purposes), we still have an opportunity to remake this API into something more maintainable.
As a first step, this PR provides new endpoints below `/rates/v1/` that implement reading of rate data via the existing report logic, but with `?rates=only` implied. This is not exactly what we want to have here in the end (there are still lots of `"resources": []` in the JSON outputs of these new endpoints), but it's enough to migrate CBR over to these new endpoints for their …

provide a stub implementation for a separate rate data API

---

pkg/plugins/capacity_sapcc_ironic.go

Extend the allowed ironic node names to matches cases like:
* node001-st001
* nodeswift01-md001
Checklist:

Ironic capacity plugin

---

pkg/plugins/capacity_sapcc_ironic.go

[ironic] capacity plugin needs to support a new naming convention

---

docs/operators/config.md
pkg/core/config.go
pkg/plugins/capacity_nova.go
pkg/plugins/capacity_sapcc_ironic.go

This more fine-grained reporting is required because billing/controlling wants to match capacity reported by us with the data in our DCIM tooling. The only active user of the aggregate-level subcapacities is Elektra; I will make sure that the respective change in Elektra gets deployed in synchrony.
This commit also changes the upper limit for instance capacity from `10000 * az_count` to `10000 * matching_aggregate_count`, since in our deployment the assumed hard limit of 10000 applies at the vCenter level, i.e. at the level of matching aggregates.
Checklist:
**Please do not merge this without my approval.** We need to land the respective UI change in Elektra first.

capacity-nova: expose hypervisors as subcapacities (instead of aggregates)

---

docs/operators/config.md
pkg/core/cluster.go
pkg/core/config.go
pkg/core/plugin.go
pkg/plugins/discovery_list.go
pkg/plugins/discovery_static.go
pkg/test/discovery.go
pkg/util/datatypes.go

On its surface, this is just cleaner separation of concerns. The pkg/core module should not have to know any types that are only relevant to the internals of individual plugin implementations.
The bigger picture is that I want to get test coverage for the config loading and cluster assembling code, by also using it to set up test scenarios. This means constructing test plugins in the usual way, from configuration. Without this change, we would have to bleed test-only types into pkg/core, which I find excessively ugly.
This change is a proof-of-concept for the approach. If this proves to work, I will also adjust the QuotaPlugin and CapacityPlugin interfaces in the same way.

move plugin-specific config types into the DiscoveryPlugins themselves

---

docs/operators/config.md
pkg/core/cluster.go
pkg/core/config.go
pkg/core/plugin.go
pkg/plugins/capacity_cinder.go
pkg/plugins/capacity_manila.go
pkg/plugins/capacity_manual.go
pkg/plugins/capacity_nova.go
pkg/plugins/capacity_prometheus.go
pkg/plugins/capacity_sapcc_cfm.go
pkg/plugins/capacity_sapcc_ironic.go
pkg/test/discovery.go
pkg/test/plugin.go

Same approach and reasoning as in #275.
Checklist:

move plugin-specific config types into the CapacityPlugins themselves

---

docs/operators/config.md
pkg/collector/scrape_test.go
pkg/core/cluster.go
pkg/core/config.go
pkg/core/constraints_test.go
pkg/core/plugin.go
pkg/plugins/capacity_manila.go
pkg/plugins/capacity_prometheus.go
pkg/plugins/cfm.go
pkg/plugins/cinder.go
pkg/plugins/client_manila.go
pkg/plugins/client_prometheus.go
pkg/plugins/cronus.go
pkg/plugins/designate.go
pkg/plugins/keppel.go
pkg/plugins/manila.go
pkg/plugins/neutron.go
pkg/plugins/nova.go
pkg/plugins/swift.go
pkg/test/plugin.go

Same approach and reasoning as in #275 and #279. Since this is the last PR in this series, I did some additional cleanup of old cruft from `pkg/core/config.go`.
Checklist:

move plugin-specific config types into the QuotaPlugins themselves

---

docs/operators/config.md
internal/plugins/manila.go

@Carthaca Can you please check whether I understood the requirement correctly? Especially the part where I'm assuming that shares managed by Manila are _never_ tagged as `volume_type="dp"` and that Snapmirror backups are _always_ tagged as `volume_type="dp"`. Also, is `snapmirror_capacity` ok as a user-facing resource name? I'm willing to take your suggestions if you have a better idea.

sharev2: add "snapmirror_capacity" resource (usage reporting only)

---

internal/api/quota_updater.go
internal/collector/capacity.go
internal/collector/keystone.go
internal/collector/metrics.go
internal/collector/ratescrape.go
internal/collector/scrape.go
internal/collector/scrape_test.go
internal/core/cluster.go
internal/core/constraints_test.go
internal/core/plugin.go
internal/datamodel/apply_backend_quota.go
internal/plugins/capacity_cinder.go
internal/plugins/capacity_manila.go
internal/plugins/capacity_manual.go
internal/plugins/capacity_nova.go
internal/plugins/capacity_prometheus.go
internal/plugins/capacity_sapcc_ironic.go
internal/plugins/cinder.go
internal/plugins/cronus.go
internal/plugins/designate.go
internal/plugins/discovery_list.go
internal/plugins/discovery_static.go
internal/plugins/keppel.go
internal/plugins/manila.go
internal/plugins/neutron.go
internal/plugins/nova.go
internal/plugins/swift.go
internal/test/discovery.go
internal/test/plugin.go
main.go

With this change, we only need the ProviderClient/EndpointOpts pair once during initialization. Afterwards, the plugins maintain their connections to the respective OpenStack services independently. (Note that the underlying ProviderClient is still shared between all ServiceClient instances so constructed, so this does not affect token rotation and such.)
The motivation for this change is that it will enable me to move `AuthToOpenstack` out of `Cluster.Connect`, which then makes the rest of that function testable.
The main reason why I did not do it like this from the start is that, very early on, Limes was intended to function with only a partial set of backend services present (which can happen during buildup of a new OpenStack cluster). This capability is long since gone, since there …

retain gophercloud.ServiceClient instances in plugins

---

internal/api/api_test.go
internal/api/quota_updater.go
internal/collector/capacity_test.go
internal/collector/collector.go
internal/collector/consistency_test.go
internal/collector/keystone_test.go
internal/collector/metrics.go
internal/collector/ratescrape.go
internal/collector/ratescrape_test.go
internal/collector/scrape.go
internal/collector/scrape_test.go
internal/core/cluster.go
internal/core/constraints_test.go
internal/core/plugin.go
internal/plugins/cinder.go
internal/plugins/cronus.go
internal/plugins/designate.go
internal/plugins/keppel.go
internal/plugins/manila.go
internal/plugins/neutron.go
internal/plugins/nova.go
internal/plugins/swift.go
internal/test/discovery.go
internal/test/plugin.go
main.go

The QuotaPlugin interface used to be built on the assumption that `pluginTypeID == serviceType` for each plugin. This assumption is broken in the tests, where the same generic plugin gets instantiated multiple times to test different subvariants in the same test.
The plugin loading code is already aware of the distinction between `pluginTypeID` and `serviceType`, but while trying to convert the testcases to load plugins from config, I ran into some places where the plugin implementations themselves rely on `pluginTypeID == serviceType`. This commit removes this assumption, by passing in `serviceType` or `allServiceInfos` from outside where required.

parametrize QuotaPlugin interface by service type

---

docs/operators/config.md
internal/plugins/capacity_manila.go

@chuan137 @Carthaca I saw from your meeting minutes that this is appearing in prod now, so I'm getting ready to start using it in Limes. Please let me know when you're done with the rollout.
Checklist:

capacity-manila: consider "hardware_state" for capacity counting

---

internal/api/fixtures/cluster-get-west-no-resources.json
internal/api/fixtures/cluster-get-west-with-overcommit.json
internal/api/fixtures/cluster-get-west.json
internal/api/fixtures/start-data-minimal.sql
internal/api/fixtures/start-data.sql
internal/collector/capacity.go
internal/collector/capacity_test.go
internal/collector/consistency.go
internal/collector/consistency_test.go
internal/collector/fixtures/checkconsistency0.sql
internal/collector/fixtures/checkconsistency1.sql
internal/collector/fixtures/checkconsistency2.sql
internal/db/migrations.go
internal/db/models.go
internal/reports/cluster.go

In preparation for splitting the capacity scrape job into separate tasks for each capacitor.
The changes in the API response fixtures emerge because we now only report those scrape timestamps that are actually relevant to the data displayed, instead of just all the timestamps all the time.

move capacity scrape timestamps from cluster_services to cluster_capacitors

---

internal/collector/collector.go
internal/collector/ratescrape.go
internal/collector/scrape.go

I want to reuse this in the capacity scrape.
Also, `scrapeTask` gets renamed to `projectScrapeTask` because I will be adding another type `capacityScrapeTask` next to it.

collector: add TaskTiming type

---

internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/scrape.go
internal/collector/scrape_test.go
internal/core/data.go
internal/core/plugin.go
internal/plugins/archer.go
internal/plugins/capacity_cinder.go
internal/plugins/capacity_manila.go
internal/plugins/capacity_manual.go
internal/plugins/capacity_nova.go
internal/plugins/capacity_prometheus.go
internal/plugins/capacity_sapcc_ironic.go
internal/plugins/cinder.go
internal/plugins/designate.go
internal/plugins/keppel.go
internal/plugins/manila.go
internal/plugins/neutron.go
internal/plugins/nova.go
internal/plugins/swift.go
internal/test/plugins/capacity_static.go
internal/test/plugins/quota_autoapproval.go
internal/test/plugins/quota_generic.go

Depending on the resource, scraping can now return capacity and usage data either for the entire region, or broken down by AZs. This distinction is represented by the enum type `core.Topological`. Quota stays affixed to the regional level for now (i.e. one number that applies across all AZs), since there is no committed requirement to support AZ quota in the backend.
The frontend does not change in any way at this point. This change is specifically about enhancing the interface between Limes internals and plugins to the point that whatever changes end up being done in the frontend can be supported.
Some more details are in the commit messages.
**Update:** I have tested that the new plugin implementations yield the same results. There are some exceptions for `sharev2/share_capacity` and …

add full AZ awareness to plugin scraping interfaces

---

docs/operators/config.md
docs/users/api-spec-resources.md
internal/core/resource_behavior.go
internal/reports/project.go

This is the very first piece of the commitments API. More stuff is ongoing in the `commitments` branch, but I will be splitting off small pieces like this to progressively unblock UI development.

add config options for commitment API, show CommitmentConfig in project reports

---

docs/users/api-spec-resources.md
internal/api/audit.go
internal/api/commitment.go
internal/api/commitment_test.go
internal/api/core.go
internal/api/fixtures/start-data-commitments.sql
internal/core/config.go
internal/datamodel/confirm_project_commitments.go
internal/db/migrations.go
internal/db/models.go
internal/reports/filter.go
internal/test/mock_validator.go
internal/test/setup.go

@VoigtS Please take a look. This should be enough API to allow your work to progress.
~~This PR is currently in draft status because the test suite is missing.~~ Test suite is done as far as I can tell.

add minimum viable API for commitments

---

internal/api/fixtures/start-data-commitments.sql
internal/api/fixtures/start-data-inconsistencies.sql
internal/api/fixtures/start-data.sql
internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/consistency_test.go
internal/collector/fixtures/checkconsistency-pre.sql
internal/collector/fixtures/checkconsistency0.sql
internal/collector/fixtures/checkconsistency1.sql
internal/collector/fixtures/checkconsistency2.sql
internal/collector/fixtures/scandomains1.sql
internal/collector/fixtures/scrape0.sql
internal/collector/keystone_test.go
internal/collector/ratescrape_test.go
internal/collector/scrape_test.go
internal/datamodel/project_resource_update.go
internal/db/migrations.go
internal/db/models.go
internal/test/setup.go

For various computations esp. relating to commitment confirmation, it will be necessary to model AZ-aware capacity, quota and usage data in the database. We currently have `project_services` below `projects` and `project_resources` below `project_services`. I want to attach a new table `project_az_resources` below `project_resources` in the same way (same for cluster level and potentially also domain level).
To avoid duplicating the current `(service_id, name)` key from the resources table into the new table, this PR adds a numeric `id` column as primary key to the resources tables, same as for most other tables.

add ID columns to *_resources tables

---

internal/api/fixtures/cluster-get-west-with-overcommit.json
internal/api/fixtures/cluster-get-west.json
internal/api/fixtures/start-data-commitments.sql
internal/api/fixtures/start-data-inconsistencies.sql
internal/api/fixtures/start-data.sql
internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/scrape.go
internal/collector/scrape_test.go
internal/core/data.go
internal/datamodel/project_resource_update.go
internal/db/migrations.go
internal/db/models.go
internal/db/setupdate.go
internal/test/plugins/quota_generic.go

The new tables are only filled and maintained right now, but not used. Once this change is rolled out, I will do the next wave where this data gets used in reports, and then the old fields in `cluster_resources` and `project_resources` will be deleted once they are not used anymore.

add AZ-aware resource records on the DB level

---

internal/api/api_test.go
internal/api/fixtures/start-data-commitments.sql
internal/api/fixtures/start-data-inconsistencies.sql
internal/api/fixtures/start-data.sql
internal/api/projects.go
internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/metrics.go
internal/collector/scrape.go
internal/collector/scrape_test.go
internal/core/data.go
internal/db/migrations.go
internal/db/models.go
internal/plugins/capacity_cinder.go
internal/plugins/capacity_manila.go
internal/plugins/capacity_nova.go
internal/plugins/capacity_sapcc_ironic.go
internal/plugins/utils.go
internal/reports/cluster.go
internal/reports/domain.go
internal/reports/inconsistency.go
internal/reports/project.go
internal/reports/utils.go
internal/test/plugins/capacity_static.go

As a followup to #370, this changeset moves all uses of AZ-aware data from the sum fields on the resources to the AZ resources tables, and then removes the sum fields that are now unused.
The one exception is the `project_resources.quota` field. Since the old quota distribution model is not AZ-aware, we continue storing quota on the resource level for now. The new quota distribution model will use the prepared `project_az_resources.quota` field once it arrives.

finish conversion to AZ-aware DB records

---

go.mod
go.sum
internal/api/api_test.go
internal/api/core.go
internal/api/domains.go
internal/api/fixtures/project-list-with-v2-api.json
internal/api/fixtures/start-data.sql
internal/api/projects.go
internal/api/quota_updater.go
internal/reports/filter.go
internal/reports/project.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/report_cluster.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/report_project.go
vendor/modules.txt

Since this increases the report size substantially, this is gated behind the HTTP header `X-Limes-V2-API-Preview: per-az` for now, which will only be used by clients that actually need the AZ breakdown.
The API spec does not reflect this, since this is currently a "hidden API". It will become fully official when we bump the API to v2. At that point, I will also update the API spec to reflect these new capabilities.

add new PerAZ field to ProjectResourceReport

---

go.mod
go.sum
internal/api/api_test.go
internal/api/fixtures/cluster-get-west-with-overcommit-and-v2-api.json
internal/api/fixtures/cluster-get-west-with-v2-api.json
internal/reports/cluster.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/report_cluster.go
vendor/modules.txt

Same behavior as for ProjectResourceReport: It's gated behind the "v2 preview" feature flag. Also, this bumps go-api-declarations twice because I realized how many fields were missing from ClusterAZResourceReport halfway through.

fill PerAZ field in ClusterResourceReport

---

internal/collector/scrape.go
internal/collector/scrape_test.go
internal/test/plugins/quota_noop.go

This is a useful invariant to uphold to simplify reporting queries, but it could be violated by quota plugins that calculate usage by counting or summing, where no usage in any AZ would be reported if there are no items to count or sum in an empty project.

ensure that each project_resource has at least one project_az_resource

---

main.go

The API core file states the following:
`r.Methods("DELETE").Path("/v1/domains/{domain_id}/projects/{project_id}/commitments/{id}").HandlerFunc(p.DeleteProjectCommitment)`
The DELETE Method is currently not allowed in the CORS config. This PR aims to fix it.

CORS: Allow DELETE method

---

docs/operators/config.md
internal/collector/fixtures/scrape_metrics.prom
internal/collector/fixtures/scrape_metrics_skipzero.prom
internal/collector/scrape.go
internal/collector/scrape_test.go
internal/core/config.go
internal/db/migrations.go
internal/db/models.go
internal/util/datatypes.go
internal/util/timeseries.go
internal/util/timeseries_test.go

We need this data to evaluate the autogrow quota distribution algorithm later on.
This is split into two commits which I recommend reviewing separately.

add project_az_resources.historical_usage and fill during scraping 

---

docs/operators/config.md
internal/plugins/capacity_nova.go
internal/plugins/nova/flavor_selection.go
internal/plugins/nova/hypervisor_selection.go

This will be reused with the upcoming other Nova capacity plugin, and also this will need a denylist soon.
Please merge this together with the respective PR in the secrets repo.

add type nova.FlavorSelection

---

docs/users/api-spec-resources.md
internal/api/commitment.go
internal/api/commitment_test.go
internal/api/core.go
internal/api/utils.go
internal/test/setup.go
main.go

productionChecklist:
This PR introduces commitment transfers from a source to a target project.
Two API's will be implemented:

Introduce TransferCommitment API

---

go.mod
go.sum
internal/api/commitment.go
internal/api/commitment_test.go
vendor/github.com/sapcc/go-api-declarations/bininfo/argument.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/commitment.go
vendor/modules.txt

This was more complicated than I anticipated, so I would appreciate a second set of eyes.

allow project admins to delete commitments up to 24h after creation

---

internal/api/commitment.go
internal/api/commitment_test.go
internal/datamodel/allocation_stats.go
internal/datamodel/apply_computed_project_quota.go
internal/datamodel/apply_computed_project_quota_test.go
internal/datamodel/confirm_project_commitments.go

This fixes a class of bugs where, in the worst case, a malicious user could create arbitrarily many commitments, even though commitments are supposed to be bound by the available capacity. The infinite-commitment glitch would work as follows:
1. Have admin access to two projects (A and B), where project A has some non-zero usage of a resource. Project A starts out without commitments for that resource.
2. Create an immediately confirmed commitment in project A covering the full amount of used resource.
3. Move this commitment to project B.
4. Go back to step 2 and repeat ad nauseam.
The issue here is that the invariant is not just `sum_over_projects(committed) <= capacity`, but `sum_over_projects(max(committed, usage)) <= capacity`. Moving commitments between projects with different usage …

confirm available capacity when moving commitments

---

internal/api/api_test.go
internal/api/audit.go
internal/api/core.go
internal/api/projects.go

This is a very temporary API to fill the new `project_resources.max_quota_from_admin` field. I did not add this to the API spec because it's only a hidden feature for now. It will become properly documented in the v2 API that we will for sure do this year, no way that's gonna get delayed, I promise.

add PUT /v1/domains/:id/projects/:id/max-quota

---

internal/api/commitment_test.go

This is a follow up to the fix created in 8812554
The transfer commitment test now checks if the superseded and split commitments have their respective values in the database. This is a measure to avoid possible regression errors in future implementations.

Fix: transfer commitment test now validates DB values

---

docs/operators/config.md
internal/core/cluster.go
internal/core/cluster_test.go

In the long run, we want to get rid of YAML as much as possible because the landscape of YAML parser libraries in Go is just awful.

change format for quota-overrides.yaml from YAML to JSON

---

internal/api/api_test.go
internal/api/quota_updater.go
internal/core/config.go

This only applies to the obsolete HierarchicalQuotaDistribution model.

remove StrictDomainQuotaLimit feature

---

internal/collector/scrape.go

When I added this TODO months ago, I anticipated that we would put ACPQ here instead of in CapacityScrapeJob.

do not clear ProjectAZResource.Quota during scrape

---

docs/operators/config.md
docs/users/api-spec-resources.md
internal/api/api_test.go
internal/api/commitment.go
internal/api/fixtures/domain-get-france.json
internal/api/fixtures/domain-get-germany.json
internal/api/fixtures/domain-list-filtered.json
internal/api/fixtures/domain-list-with-v2-api.json
internal/api/fixtures/domain-list.json
internal/api/fixtures/project-get-berlin.json
internal/api/fixtures/project-get-details-berlin.json
internal/api/fixtures/project-get-dresden.json
internal/api/fixtures/project-get-paris.json
internal/api/fixtures/project-list-filtered.json
internal/api/fixtures/project-list-with-v2-api.json
internal/api/fixtures/project-list.json
internal/collector/capacity_scrape.go
internal/collector/metrics.go
internal/core/cluster.go
internal/core/resource_behavior.go
internal/datamodel/allocation_stats.go
internal/datamodel/resource_demand.go
internal/reports/cluster.go
internal/reports/domain.go
internal/reports/project.go
main.go

- Scaling behaviors were used as a UI hint for quota editing.
- MinNonZeroProjectQuota is a constraint that ApplyComputedProjectQuota ignores.
- Annotations was used to mark resources as "can_autoscale" for Castellum.
Also, scoping support for behaviors is removed, since all remaining ResourceBehavior attributes do not support scoping anyway.

remove obsolete ResourceBehavior fields

---

internal/api/api_test.go
internal/api/fixtures/start-data-commitments.sql
internal/api/fixtures/start-data-inconsistencies.sql
internal/api/fixtures/start-data.sql
internal/collector/capacity_scrape_test.go
internal/collector/scrape_test.go
internal/datamodel/apply_backend_quota.go
internal/datamodel/apply_computed_project_quota.go
internal/datamodel/project_resource_update.go
internal/db/migrations.go
internal/db/models.go
internal/reports/inconsistency.go

This field is redundant now: With the removal of quota bursting, there are never situations where `quota != desired_backend_quota`.

remove project_resources.desired_backend_quota field

---

internal/plugins/capacity_manila.go

This is a refactor of the "manila" capacity plugin. After its rewrite to AZ awareness last year, I never really cleaned up the implementation, so there is a bit of a weird structure where capacity for all AZs is computed in the same function even though the function cleanly factors into separate computations per AZ.
Checklist:

capacity-manila: refactor Scrape() to separate computations per AZ

---

docs/operators/config.md
internal/core/resource_behavior.go
internal/plugins/capacity_manila.go

capacity-manila: consider ResourceDemand when splitting capacity/usage between shares and snapshots

---

internal/datamodel/apply_computed_project_quota.go

This was not a problem until yesterday, when I added capacity to our only NoQuota resource (`sharev2/snapmirror_capacity`), thus giving ApplyComputedProjectQuota the prerequisite needed to actually commit this error.

do not try to compute quota for resources with NoQuota flag

---

internal/plugins/nova/flavor_translate.go

Removing the call to this method was an oversight on my part.

revert removing recordNovaPreferredName

---

internal/plugins/swift.go

As part of the project deletion process, customers are expected to delete their Swift accounts. Between the account deletion and the actual project deletion, we now get a lot of errors from limes-collect like:
```
2024/06/17 13:07:46 ERROR: could not sync object-store quotas for project monsoon3/cc-demo2: could not PUT "<account>" in Swift: expected 201/202 response, got 403 instead: Recently deleted
```
because Limes is still trying to assign base quota to these projects even though there is no Swift account to write the quota into.

plugins/swift: do not try to assign base quota to deleted Swift accounts

---

internal/datamodel/apply_computed_project_quota.go
internal/datamodel/apply_computed_project_quota_test.go

The previous implementation of ACPQ allowed quota distribution to ANY AZ if this AZ already contains base quota.
This is not desired, because the distributed quota is then unusable for the user.

fix ACPQ test cases to always take zero-valued inputs in the "any" AZ

---

docs/operators/config.md
internal/plugins/nova.go
internal/plugins/nova_subresources.go

Ref: <https://github.com/sapcc/nova/pull/469>
I tested in prod that `limes test-get-quota` returns the same output before and after the change (since no hardware-versioned quotas exist there yet).

plugins/nova: add support for hardware-versioned quota

---

docs/users/api-spec-resources.md
internal/api/commitment.go
internal/api/commitment_test.go
internal/api/core.go
internal/collector/capacity_scrape_test.go
internal/collector/commitment_cleanup_test.go
internal/db/migrations.go
internal/db/models.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/commitment.go

Because this topic bugged me, I changed the transfer_token to a proper UNIQUE constraint now. This required to change the type definitions to accept null values and code adjustments in the API logic. The migration flow is now as follows:
* drop NOT NULL setting and set default NULL value at the transfer_token column
* Update all current entries in this column from empty string to NULL
* Set the UNIQUE constraint to the column.

Add GET commitment by token endpoint with proper UNIQUE key

---

internal/plugins/capacity_nova.go

"No overcommit" can be expressed both as factor of 1 and factor of 0. The latter ensures the Go rule of "zero value must be sensible".

fix failing overcommit validation

---

docs/operators/config.md
internal/plugins/capacity_liquid.go
internal/plugins/client_liquid.go
internal/plugins/liquid.go

I believe these plugins to be feature-complete, but since the only existing LIQUID implementation is in Keppel, I cannot test most of it. `test-get-quota` against liquid-keppel works fine:
```
$ tail -n 6 config-eu-de-1.yaml
- service_type: keppel
type: liquid
params:
area: storage
endpoint_override: https://keppel.eu-de-1.cloud.sap/liquid/
$ make && env LIMES_DEBUG=true ./build/limes test-get-quota config-eu-de-1.yaml $EXAMPLE_PROJECT_ID keppel
...
{
"images": {
"Quota": 25000,
"MinQuota": null,
"MaxQuota": null,
"UsageData": {
"any": {
"Usage": 12115,
"PhysicalUsage": null,
"Subresources": null
}
}
}
}
```
(This is using the EndpointOverride config option because the service catalog entry for liquid-keppel is currently stuck in seeding hell.)
But liquid-keppel reports neither capacity …

add LIQUID support

---

go.mod
go.sum
vendor/modules.txt

Update go-api-declarations to 1.12.1. Changes the `transferToken` type of a commitment to a pointer to treat it as a unique key.

Update go api declaration dependency

---

internal/datamodel/allocation_stats.go

Rewriting from a sub-SELECT into a LEFT OUTER JOIN is something that I expected the query optimizer to be able to do, but evidently not. This change increases performance by a factor of about 70 (i.e. 7000%) in my tests on eu-de-1. EXPLAINs below before for reference (first before, then after).
```
postgres@127.0.0.1:limes> EXPLAIN (ANALYZE,BUFFERS) SELECT pr.id, par.az, par.usage, par.historical_usage, (SELECT COALESCE(SUM(pc.amount), 0) FROM project_commitments pc WHERE pc.az_resource_id = par.id AND pc.state = 'active') FROM project_services ps JOIN project_resources pr ON pr.service_id = ps.id JOIN project_az_resources par ON par.resource_id = pr.id WHERE ps.type = 'compute' AND pr.name = 'cores';
+---------------------------------------------------------------------------------------- …
```

optimize SQL query in collectAZAllocationStats()

---

internal/plugins/manila.go

We now have a region that legitimately does not have any snapshots.

plugins/manila: do not fail on missing snapshot data

---

docs/liquids/index.md
docs/liquids/neutron.md
docs/liquids/octavia.md
internal/liquids/neutron/liquid.go
internal/liquids/octavia/client.go
internal/liquids/octavia/liquid.go
internal/liquids/utils.go
main.go

To simplify, the Neutron liquid eschews the extension querying that the old QuotaPlugin does, and instead looks at the default quota set to observe which resources exist.
I checked both of these against QA (both to get quota/usage and set quota) and they work as intended.

add liquids for neutron and octavia

---

docs/operators/config.md
internal/core/cluster.go
internal/core/cluster_test.go
internal/core/fixtures/quota-overrides-no-renaming.json
internal/core/fixtures/quota-overrides-with-renaming.json

It is useful for us to use the API-level names here because:
1. some quota overrides are shared between all clusters (so renaming must be carefully coordinated here, same as for the API), and
2. this config file is maintained by a wider operator audience (so any renaming here should be properly communicated with advance notice).

parse quota-overrides using API-level resource renaming

---

Makefile
Makefile.maker.yaml

Currently, only `internal/plugins` is excluded because we test plugin implementations manually. This includes `internal/liquids/*` based on the same reasoning.

update coverage check exclusion rule

---

internal/datamodel/allocation_stats.go
internal/datamodel/confirm_project_commitments.go

I already tried to fix this in 5f75541332d84fc69f669f7eef8257673b10e1a4, but it did not go all the way. We saw this in a debug log:
```
DEBUG: checking CanMoveExistingCommitment in compute/ram/eu-de-1d: resourceID = 3296 -> 187489, amount = 412252
DEBUG: CanAcceptCommitmentChanges: forbidden by commitment target 24429662 > usage 23889216 in resourceID = 3296
```
The problem here is that `committed > usage` was evaluated in the project where `committed` shrinks, even though it is only relevant in the project where `committed` expands.

fix commitment move in overcommitted AZ

---

docs/liquids/cinder.md
docs/liquids/index.md
docs/liquids/manila.md
internal/liquids/cinder/capacity.go
internal/liquids/cinder/liquid.go
internal/liquids/cinder/usage.go
internal/liquids/manila/capacity.go
internal/liquids/manila/liquid.go
internal/liquids/manila/sharetype.go
internal/liquids/manila/usage.go
internal/liquids/types.go
internal/liquids/utils.go
internal/plugins/capacity_manila.go
main.go
vendor/github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/volumetypes/doc.go
vendor/github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/volumetypes/requests.go
vendor/github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/volumetypes/results.go
vendor/github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/volumetypes/urls.go
vendor/modules.txt

For the most part, this is a straight port of the respective QuotaPlugin and CapacityPlugin implementations (so I recommend reading these side-by-side with the new code as necessary to follow along), but I used the opportunity to streamline some parts of the implementation. Most notably:
- The Cinder liquid discovers available volume types via the API instead of taking them as configuration.
- In the Manila liquid, I introduced new terminology to more clearly distinguish `VirtualShareType` (the share type names that appear in Limes resources) from `RealShareType` (the share type names that are used on the Manila API).

add liquid-cinder and liquid-manila

---

internal/api/translation_test.go
internal/core/translation_rule.go

We need this on the capacity resources, not on the volumes/snapshots resources.

fix TranslationRule placement for Cinder

---

internal/api/api_test.go
internal/api/commitment.go
internal/api/projects.go
internal/api/rate_updater.go
internal/collector/metrics.go
internal/core/cluster.go
internal/core/config.go
internal/core/name_mapping.go
internal/core/rate_behavior.go
internal/core/resource_behavior.go
internal/datamodel/quota_overrides.go
internal/reports/cluster.go
internal/reports/domain.go
internal/reports/filter.go
internal/reports/inconsistency.go
internal/reports/project.go

This is the same as core.ResourceBehavior, but for rates. I'm adding this now to support rate renaming in the same way as resource renaming (as a prerequisite for transitioning the Cronus plugin to LIQUID in the same way as for the resource-bearing plugins that were already converted).
There is one clearly ugly part where one specific error message in the PUT endpoint for rate limits now generates a 500 error in a specific case that should be a 4xx error. I don't care about fixing this in the v1 API because nobody is using this at the moment anyway. In the v2 API, we will transition PUT on rate limits to only work on one rate at the time in order to simplify the entire RateUpdater thing.

add core.RateBehavior

---

docs/users/api-spec-resources.md
internal/api/audit.go
internal/api/commitment.go
internal/api/commitment_test.go
internal/api/core.go

This PR aims to introduce the POST API to convert a supported commitment from a source to a target resource.

Add POST API to convert a commitment to a target Resource

---

internal/liquids/cinder/liquid.go
internal/liquids/cinder/usage.go

liquid-cinder only reports resources for public volume types, so private volume types will be counted as unknown by ReportUsage(). Private volume types can legitimately occur in QA, as leftovers from Tempest runs. Instead of failing when any volume or snapshot refers to a private volume type, we now emit metrics reporting how much unknown stuff was ignored. My plan is to have an alert about these unbilled resources, but only on prod.
I tested this in QA against the one project that currently has volumes like this, and it looks good there.

liquid-cinder: do not fail on unknown volume types

---

docs/users/api-spec-resources.md
internal/api/core.go
internal/api/liquid.go
internal/api/liquid_test.go
internal/core/plugin.go
internal/plugins/capacity_liquid.go
internal/plugins/capacity_manual.go
internal/plugins/capacity_nova.go
internal/plugins/capacity_prometheus.go
internal/plugins/capacity_sapcc_ironic.go
internal/plugins/liquid.go
internal/plugins/nova.go
internal/test/plugins/capacity_static.go
internal/test/plugins/quota_generic.go
internal/test/plugins/quota_noop.go

Add api endpoint to render request payloads for querying the LIQUID api

---

internal/plugins/capacity_nova.go
internal/plugins/capacity_sapcc_ironic.go
internal/plugins/nova.go
internal/plugins/nova/flavor_translate.go

Just skipping the flavors when enumerating split flavors is not enough. We need to actively ignore quotas and instances associated with those ignored flavors as well.
Checklist:

plugins/nova: fix ignoring of baremetal instances in liquid-ironic compat mode

---

internal/liquids/archer/liquid.go
internal/liquids/cinder/liquid.go
internal/liquids/cronus/liquid.go
internal/liquids/designate/liquid.go
internal/liquids/ironic/liquid.go
internal/liquids/manila/liquid.go
internal/liquids/neutron/liquid.go
internal/liquids/octavia/liquid.go
internal/liquids/swift/liquid.go

This is a new capability added in go-api-declarations 1.13.0 which will eventually become mandatory in Limes.
While I was at it, I replaced references to go-api-declarations/limes in the liquids' implementation with the synonymous types in go-api-declarations/liquid.

liquids: add topology declaration

---

internal/liquids/manila/capacity.go
internal/util/algorithms.go
internal/util/algorithms_test.go

I need to use this function in liquid-cinder as well.
The new implementation is the same as the old one, except that the last paragraph is rewritten to remove references to Manila-specific identifiers.

generalize DistributeDemandFairly()

---

internal/liquids/cinder/capacity.go
internal/liquids/cinder/liquid.go

This diff is way more intrusive than I would have liked, but the basic structure is retained. Instead of drilling down into volume type and then into AZ, we need to drill down into volume backend name and AZ.
Then at the lowest level, a single volume backend name can be shared by multiple volume types, so the reported capacity and usage need to be balanced by demand (in the same way as we do in liquid-manila between share capacity and snapshot capacity). This then gets bubbled back up all the way.
Checklist:

liquids/cinder: fix capacity for volume types sharing the same backend name

---

internal/liquids/ironic/capacity.go

See code comment for details.
Checklist:

liquid-ironic: improve peak memory usage

---

docs/operators/config.md
internal/api/api_test.go
internal/api/commitment.go
internal/api/commitment_test.go
internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/commitment_cleanup_test.go
internal/collector/scrape.go
internal/collector/scrape_test.go
internal/collector/sync_quota_to_backend.go
internal/core/data.go
internal/core/plugin.go
internal/core/resource_behavior.go
internal/datamodel/apply_computed_project_quota.go
internal/datamodel/apply_computed_project_quota_test.go
internal/db/migrations.go
internal/db/models.go
internal/plugins/capacity_liquid.go
internal/plugins/liquid.go
internal/plugins/nova.go
internal/plugins/utils.go
internal/test/plugins/quota_generic.go
internal/test/plugins/quota_noop.go
main.go

This implementation handles the introduction of resource topologies. This allows the handling of synchronizing AZ-aware and AZ-separated quotas with the backend. 
The plugins will check if a liquid provides a valid toplogy. Invalid AZ's that are detected during scrapes will be rejected. Scraped AZ-separated quota will be included into the `backend_quota` column that resides in the `project_az_resources` table. From limes quota will then be synced with the backend if necessary. The `backend_quota` values will then be updated to the calculated `quota` values.
Things to note:
~* The AZ key sorting in the uitlity functions might be able to be improved.~
~* `MatchLiquidReportToTopology` might collect the errors for all resources instead of failing at the first mismatch.~
~* SetQuota required a …

Add support for AZ-separated quotas

---

internal/collector/scrape_test.go
internal/plugins/utils.go

The previous implementation checked against a copied value. The default value was therfore discarded which resulted in an undesired error state.

Fix: Check resource toplogy

---

internal/plugins/capacity_liquid.go
internal/plugins/liquid.go

The previous implementation does not expect missing resources from scrapes, which is why the execution of the `MatchLiquidReportToTopology` gets pushed down after this check executed.

fix: check missing resource reports before checking toplogy

---

internal/reports/cluster.go
internal/reports/project.go

This is a temporary fix to ensure that AZSeparatedTopology resources do not get checked for their ANY az. A proper test case and a proper handling will be implemented as a follow up.

fix: project report. AZSeparatedToplogy does not provide any az

---

internal/collector/scrape_test.go
internal/collector/sync_quota_to_backend.go
internal/datamodel/apply_computed_project_quota.go

SyncQuotaToBackend: fix overall resource quota for AZSeparated resources

---

internal/collector/scrape.go
internal/collector/scrape_test.go
internal/datamodel/project_resource_update.go
internal/test/plugins/quota_generic.go

I'm seeing a lot of this in the DB right now:
```
psql> SELECT pr.name, pr.quota, pr.backend_quota, par.az, par.quota, par.usage
FROM project_resources pr
LEFT OUTER JOIN project_az_resources par ON par.resource_id = pr.id
WHERE pr.service_id = (
SELECT id FROM project_services
WHERE type = 'ceph' AND quota_desynced_at IS NOT NULL
ORDER BY quota_desynced_at LIMIT 1
);
+----------------+--------+---------------+----------+-------+-------+
| name           | quota  | backend_quota | az       | quota | usage |
|----------------+--------+---------------+----------+-------+-------|
| local-premium  | <null> | 0             | qa-de-1a | 0     | 0     |
| local-premium  | <null> | 0             | qa-de-1b | 0     | 0     |
| local-premium  | <null> | 0             | qa-de-1d | 0     | 0     |
| …
```

avoid backend_quota edit war for AZSeparatedResourceTopology

---

docs/operators/config.md
docs/users/api-spec-rates.md
docs/users/api-spec-resources.md

This PR fixes a URL to the table of contents icon in docs

Fix docs TOC icon URL

---

internal/api/api_test.go
internal/api/fixtures/cluster-get-az-separated.json
internal/api/fixtures/domain-list-az-separated.json
internal/api/fixtures/project-list-az-separated.json
internal/api/fixtures/start-data-az-separated.sql
internal/collector/scrape_test.go
internal/reports/cluster.go
internal/reports/domain.go
internal/reports/project.go

As promised in previous PRs. A new fixture was added to cover our existing abstraction levels with one dedicated case.

Add test cases to prevent future API breaks on AZ separated changes

---

internal/liquids/nova/liquid.go
internal/liquids/nova/subresources.go
internal/liquids/nova/usage.go
main.go

Add liquid nova report usage endpoint

---

internal/liquids/ironic/capacity.go
internal/liquids/ironic/liquid.go

The assignment of baremetal nodes to an AZ is solved via the ID matching to resource providers. Because the resource provider IDs might mismatch to the node IDs, a manual config override will be provided for the ironic liquid.
Checklist:

add ironic node to az assignment override

---

docs/liquids/ironic.md
internal/liquids/ironic/capacity.go
internal/liquids/ironic/liquid.go

New baremetal deployments in eu-de-1 cause memory allocation spikes for the ironic liquid. 
We already had an optimization for the taxing node details in [in ths commit](https://github.com/sapcc/limes/pull/608/files).
I would like to try and reduce hte paging limit for node details. Local tests are too fluctuating to make a clear difference, the memory allocations to each page seem to decrease tho. If this has no notable impact, I will revert this change.

adjust ironic limit

---

docs/liquids/cinder.md
internal/liquids/cinder/capacity.go
internal/liquids/cinder/liquid.go

This PR aims to support FCD checks from Pools to VolumeTypes via the `StorageProtocol` and the `QualityType`.
The old way of matching against the `volumeBackendName` is still available for the current Pools.
The catch on the new approach is that `VolumeTypes` might a `Encryption` attribute attachted to them at some point. Those will have the same `StorageProtocol` and `QualityType` as the the one without encryption.
This behavior is similar how we treat `volumeBackendName` already. The collected Pool capacity will just be split into the matching volumeTypes.
I tested the implementation against the cluster and yes, we do retrieve non-matching Pools into the resultset now. 
Please have a look at this, there might be optimization that I can do. Other than that I will update the documentation …

Liquid Cinder: Add FCD support

---

internal/liquids/cinder/capacity.go

~~This is a fix to the fcd topic.
In QA it worked, because both, `volume_backend_name` and `storage_protocol + storage_quality_type`.
In `ap-sa-2` the succession of the regular pool check and the fcd pool check is active.~~
EDIT: The implementation as it is works, because during analysis I thought we loop over the infos and not over the pools which threw me off (see last commits). Instead, we add missing info to the output logs.
Checklist:

fix fcd pool check

---

internal/liquids/manila/liquid.go

Move the definition of the query out to manila service to have the
logic in faster control of the team that operates manila.
query was added in https://github.com/sapcc/helm-charts/pull/7690
--
those metrics are live in all regions and ready to be used

[liquid][manila] use generic query for snapmirror capa

---

internal/datamodel/apply_computed_project_quota.go
internal/datamodel/apply_computed_project_quota_test.go

Acpq quota overrides bug

---

internal/collector/fixtures/mail_delivery.sql
internal/collector/mail_client.go
internal/collector/mail_delivery.go
internal/collector/mail_delivery_test.go

This implementation handles the way of how we deal with projects that don't maintain any metadata.
If no subproject/project or domain delivers any metadata, the queue will be freed of the mail request and a log will be placed.

[mail] handle queue for projects without metadata

---

docs/users/api-spec-resources.md
internal/api/commitment.go
internal/api/commitment_test.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/commitment.go

If this implementation fits the desired outcome, I will create a PR for go-api-declarations before this gets merged.

commitments: Add notify on confirm (mail) support

---

main.go

As the comment explains, I want to have this to temporarily block email notifications for expiry from being sent, until we have the "Renew" button ready on the UI.

add hidden feature flag to block expiry notifications temporarily

---

internal/liquids/manila/capacity.go

liquid-manila: add empty AZResourceCapacityReports to comply with limes requirements

---

internal/collector/expiring_commitments.go
internal/collector/fixtures/mail_expiring_commitments.sql
main.go

During a checkup I noticed that superseded commitments are currently processed by the expiration mailer.
This PR fixes this.

[mail] do not include superseded commitments

---

internal/collector/capacity_scrape_test.go
internal/collector/expiring_commitments.go
internal/collector/expiring_commitments_test.go
internal/datamodel/confirm_project_commitments.go

The implementation was created with the backend goggles on. However, the location stats need to be resolved to their api equivalents as they do in the API's.

[mail] Fix serviceType and resourceName to their api variants

---

internal/collector/expiring_commitments.go
internal/collector/expiring_commitments_test.go
internal/collector/fixtures/mail_expiring_commitments.sql

I noticed that the mail for expiring commitments also reports short term commitments, which shouldn't be the case.
The original implementation had in mind to also inform about already expired commitments to create awareness, but it will rather create confusion also in conjuction with the output of the UI. Which is why I limit the mailing to active commitments.

[mail] only report active commitments

---

internal/liquids/manila/liquid.go

The update to gophercloud 2.7.0 causes the first found Manila URL to be returned, which is the v1 API. This PR is a workaround for this behavior and enforces the use of the v2 API throughout the LIQUID.

add manila URL replacement

---

internal/liquids/manila/liquid.go

The previous implementation was a hacky workaround which ensured that accidental prod deployments don't create a fallout. This approach cleaner, because it limits the available clients to sharev2.

[manila] enforce v2 client

---

internal/collector/fixtures/capacity_data_metrics.prom
internal/collector/fixtures/ratescrape_metrics.prom
internal/collector/fixtures/ratescrape_metrics_skipzero.prom
internal/collector/fixtures/scrape_data_metrics.prom
internal/collector/fixtures/scrape_data_metrics_skipzero.prom
internal/collector/fixtures/scrape_metrics.prom
internal/collector/metrics.go
internal/collector/scrape.go
internal/collector/sync_quota_to_backend.go
internal/core/plugin.go
internal/plugins/liquid.go

When the internal service types were "compute", "network" etc., we had ProductName in order to have "nova", "neutron" etc. on metrics to aid in alert routing to the respective service channels. Since the DB service types are now changed to already be "nova", "neutron" etc., we can get rid of this.

remove ServiceInfo.ProductName

---

internal/collector/keystone.go
internal/db/migrations.go

With the first wave of commitments expiring in prod, we now often see project deletions failing due to the ON DELETE RESTRICT constraint on project_commitments. This is generally fine; we do not want to delete a project that has active commitments. But if the only existing commitments are in states `superseded` or `expired`, this change will allow the project deletion to proceed without manual intervention.

do not fail project deletion on superseded/expired commitments

---

docs/operators/config.md
docs/operators/metrics.md
internal/api/commitment.go
internal/api/fixtures/start-data-commitments.sql
internal/api/fixtures/start-data-small.sql
internal/api/fixtures/start-data.sql
internal/api/liquid.go
internal/api/liquid_test.go
internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/consistency.go
internal/collector/consistency_test.go
internal/collector/expiring_commitments_test.go
internal/collector/fixtures/capacity_metrics.prom
internal/collector/fixtures/capacity_scrape_with_commitments.sql
internal/collector/fixtures/checkconsistency0.sql
internal/collector/fixtures/checkconsistency1.sql
internal/collector/fixtures/checkconsistency2.sql
internal/collector/mail_delivery_test.go
internal/collector/metrics.go
internal/core/cluster.go
internal/core/config.go
internal/core/plugin.go
internal/db/migrations.go
internal/db/models.go
internal/plugins/capacity_liquid.go
internal/reports/cluster.go
internal/test/setup.go

Checklist:
This PR has the next level of changes towards a common configuration for `services[]` and `capacitors`:
* we remove the `cluster_capacitors` table and shift the columns to the `cluster_services`
* we move around the `service_type` to be on the same level as for `services[]` already
* we shift some of the wording - the capacitors only really exist on app layer/ configuration after this change
* as a result, we assume that the `service_type` of a `service` and `capacitor` are the same if they belong together
naturally, this needs a companion PR for the deployment. I tested again locally and all the results in the DB looked the same.

remove cluster_capacitors from DB

---

internal/liquids/nova/capacity.go

We have a new AZ in prod which does not have compute capacity yet, so we are running into this problem for the first time.
Checklist:

liquid-nova: fix missing AZ

---

internal/api/fixtures/start-data-commitments.sql
internal/api/fixtures/start-data.sql
internal/collector/capacity_scrape.go
internal/collector/capacity_scrape_test.go
internal/collector/fixtures/capacity_scrape_with_commitments.sql
internal/datamodel/allocation_stats.go
internal/datamodel/apply_computed_project_quota.go
internal/datamodel/apply_computed_project_quota_test.go
internal/db/migrations.go
internal/db/models.go

The addition of the second AZ in Tokyo to our config is causing problems. There is no compute capacity, but because customers have seen the new AZ, they tried poking it and creating instances there. These instances will inevitably fail to spawn because there are no matching hypervisors to place them on, but the instances are still around in status `ERROR`. When ACPQ runs, it sees usage in the AZ, but no capacity to go with it, and so base quota overcommit is blocked.
This is an undesirable behavior, but we don't see a good way to prevent this situation from arising. Instances in status `ERROR` need to be reported (because they count towards the quota) and need to be in the correct AZ (because billing needs to associate them with commitments to apply the correct price).
We have an existing …

ACPQ: do not block base quota overcommit because of empty AZs in buildup

---

docs/liquids/neutron.md
internal/liquids/neutron/liquid.go

We now support dynamically registered quotas for Neutron, where we only know a prefix of the quota and not the full name. This is done so Neutron can expose network flavors as quotas, but might be used for other objects in the future. To expose these dynamic quotas we're now checking if the quota name has a prefix from a list of predefined prefixes (in addition to the lookup in the liquids already existing hardcoded list).
Checklist:

liquid-neutron: support dynamic quotas

---

internal/core/cluster.go

We saw weird inconsistencies in the liquid_version value between cluster_services and cluster_resources. We do not have enough information to analyze the problem, so this is intended to give more visibility into which updates are performed.

trace updates performed by SaveServiceInfoToDB

---

docs/liquids/index.md
docs/operators/config.md
internal/api/api_test.go
internal/api/commitment.go
internal/api/commitment_test.go
internal/api/inconsistencies_test.go
internal/api/liquid_test.go
internal/api/removed_test.go
internal/api/translation_test.go
internal/collector/capacity_scrape_test.go
internal/collector/commitment_cleanup_test.go
internal/collector/expiring_commitments_test.go
internal/collector/keystone_test.go
internal/collector/mail_delivery_test.go
internal/collector/quota_overrides_test.go
internal/collector/scrape_test.go
internal/core/cluster.go
internal/core/cluster_test.go
internal/core/config.go
internal/core/config_test.go
internal/core/liquid.go
internal/datamodel/quota_overrides_test.go
internal/test/mock_liquid_client.go
internal/test/setup.go
main.go

I have stacked some changes on top of #766 to not block tests from progressing in parallel because they might share the same service types for their mock liquids.

remove liquidServiceType (only used for testing), attempt 2

---

docs/users/api-spec-resources.md
internal/api/api_test.go
internal/api/audit.go
internal/api/core.go
internal/api/fixtures/project-get-paris-forbid-autogrowth.json
internal/api/projects.go
internal/datamodel/apply_computed_project_quota.go
internal/db/migrations.go
internal/db/models.go
internal/reports/project.go
vendor/github.com/sapcc/go-api-declarations/limes/resources/report_project.go

This implements the endpoint to enable or disable quota autogrowth for provided resources. The deconstruction of the `max-quota` endpoint will be performed when the UI is ready. There, we will remove the confusing double management of max-quota between outside and local admins (Cluster/Domain vs. Project level).
Checklist:
Before merging:
Add the `ForbidAutogrowth` attribute for the project resource report to go-api-declarations.

add endpoint: forbid-autogrowth

---

internal/collector/fixtures/scrape0.sql
internal/core/cluster.go
internal/core/cluster_test.go

We only relied on the RateInfo returned by LIQUID when creating `rates` records, but for rates that are only configured (i.e. limit only and no usage), we do not have a RateInfo. In this case, we're now putting in UnitNone and FlatTopology as reasonable fallbacks. If anything else needs to be supported in the future, we need to extend the config format.

internal/core: fix rates records created from configured rates

---

internal/api/api_test.go
internal/api/commitment.go
internal/api/projects.go
internal/collector/capacity_scrape.go
internal/collector/consistency.go
internal/collector/expiring_commitments.go
internal/collector/metrics.go
internal/collector/quota_overrides.go
internal/collector/scrape.go
internal/collector/sync_quota_to_backend.go
internal/core/cluster.go
internal/datamodel/allocation_stats.go
internal/datamodel/apply_computed_project_quota.go
internal/datamodel/confirm_project_commitments.go
internal/datamodel/project_resource_update.go
internal/datamodel/resource_demand.go
internal/db/migrations.go
internal/reports/cluster.go
internal/reports/domain.go
internal/reports/error.go
internal/reports/inconsistency.go
internal/reports/project.go
internal/test/setup.go

This PR renames
* `services=cs` to `services=s`
* `resources=cr` to `resources=r`
* `az_resources=cazr` to `az_resources=azr`
* `rates=cra` to `rates=ra`
in response to @VoigtS's comment here: https://github.com/sapcc/limes/pull/771#discussion_r2315856828
I had a brief discussion with him, he mentioned to me that @majewsky found `r` and `s` to be possibly too short for recognition. I personally found it weird to leave the old abbreviations ("why the `c`?" a new-joiner might ask) when I wanted to start on the commitment functionality. IMHO it's okay, when we use these abbreviations consistently - everywhere. The conflict of `r` between `rates` and `resources` requires a convention anyway - so please let me know your opinions.
Sidenote: I would also be fine to use this chance to switch to …

rename old cluster level table abbreviations
